# keymap_drawer.config.yaml
draw_config:
  key_w: 60
  key_h: 56
  split_gap: 10.0
  combo_w: 28
  combo_h: 26
  key_rx: 1.0
  key_ry: 1.0
  dark_mode: true
  n_columns: 1
  separate_combo_diagrams: true
  combo_diagrams_scale: 3
  inner_pad_w: 2.0
  inner_pad_h: 2.0
  outer_pad_w: 30.0
  outer_pad_h: 56.0
  line_spacing: 1.2
  arc_radius: 6.0
  append_colon_to_layer_header: true
  small_pad: 2.0
  legend_rel_x: 0.5
  legend_rel_y: 0.5
  draw_key_sides: false
  key_side_pars:
    rel_x: 0.0
    rel_y: 4.0
    rel_w: 12.0
    rel_h: 12.0
    rx: 4.0
    ry: 4.0
  svg_extra_style: |
    /* Combo box (the little key-shaped pill) */
    .combo rect {
      fill: #FFD54F;         /* bold yellow fill */
      stroke: #222;          /* dark outline for contrast */
      stroke-width: 1.6px;
    }

    /* Combo arc lines */
    .combo path {
      stroke: #FFB300;       /* stronger arc color */
      stroke-width: 2.4px;   /* thicker lines to pop more */
      opacity: 1;            /* ensure fully opaque */
    }

    /* Combo labels (text inside the combo box) */
    .combo .label {
      fill: #111;            /* dark text for readability */
      font-weight: 700;
      font-size: 10px;       /* bump if you need bigger text */
    }
  footer_text: ''
  shrink_wide_legends: 7
  style_layer_activators: true
  glyph_tap_size: 14
  glyph_hold_size: 12
  glyph_shifted_size: 10
  glyphs: {}