draw_config:
  key_w: 60
  key_h: 56
  split_gap: 10.0
  combo_w: 14
  combo_h: 13
  key_rx: 1.0
  key_ry: 1.0
  dark_mode: auto
  n_columns: 1
  separate_combo_diagrams: true
  combo_diagrams_scale: 3
  inner_pad_v: 2.0
  inner_pad_h: 2.0
  outer_pad_w: 30.0
  outer_pad_h: 56.0
  line_spacing: 1.2
  arc_radius: 6.0
  append_colon_to_layer_header: true
  small_pad: 2.0
  legend_rel_x: 0.5
  legend_rel_y: 0.5
  draw_key_sides: false
  key_side_pars:
    rel_x: 0.0
    rel_y: 4.0
    rel_w: 12.0
    rel_h: 12.0
    rx: 4.0
    ry: 4.0
  svg_extra_style: |2-
    /* overall tint */
    svg.keymap { fill: #d1d6db; }

    /* base keys */
    rect.key { fill: #3f4750; }
    rect.key, rect.combo { stroke: #60666c; }

    /* combo pill */
    rect.combo, rect.combo-separate {
      fill: #0b0038;
      stroke: #ffffff;
      stroke-width: 1.8px;
    }

    /* pressed keys in combo diagrams */
    rect.held, rect.combo.held { fill: #FFB300; }

    /* titles/footers outline for legibility */
    text.label, text.footer { stroke: black; }

    /* transparent key legends */
    text.trans { fill: #7e8184; }

    /* combo label INSIDE the pill */
    .combo .label { fill: #ff8c00; font-weight: 700; }

    /* dendron lines (only in non-separate diagrams) */
    .combo path, path.combo { stroke: #7f7f7f; }

  shrink_wide_legends: 7
  style_layer_activators: true
  glyph_tap_size: 14
  glyph_hold_size: 12
  glyph_shifted_size: 10

  glyphs: {}
