name: Draw ZMK keymaps

on:
  workflow_dispatch:
    inputs:
      make_pngs:
        description: "Also generate PNGs"
        type: boolean
        default: false
  push:
    paths:
      - "config/*.keymap"
      - "config/*.dtsi"
      - "keymap-drawer/**"

jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@v0.22.1
    permissions:
      contents: write
    with:
      keymap_patterns: "config/*.keymap"
      config_path: "keymap-drawer/keymap_drawer.config.yaml"
      output_folder: "keymap-drawer"

  png:
    if: ${{ github.event_name == 'workflow_dispatch' && inputs.make_pngs }}
    needs: draw
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - run: echo "PNG job disabled unless manually requested."
